// 
// Model definitions generated by Swako
//

// Category
public struct Category {
  public var id: Int 
  public var name: String 
}

// Tag
public struct Tag {
  public var id: Int 
  public var name: String 
}

// User
public struct User {
  public var username: String 
  public var firstName: String 
  public var lastName: String 
  public var userStatus: Int // User Status
  public var id: Int 
  public var phone: String 
  public var password: String 
  public var email: String 
}

// Pet
public struct Pet {
  public var category: Category 
  public var status: String // pet status in the store
  public var name: String 
  public var tags: Array<Tag> 
  public var photoUrls: Array<String> 
  public var id: Int 
}

// Order
public struct Order {
  public var status: String // Order Status
  public var shipDate: String 
  public var complete: Bool 
  public var petId: Int 
  public var id: Int 
  public var quantity: Int 
}

// ApiResponse
public struct ApiResponse {
  public var message: String 
  public var code: Int 
  public var type: String 
}

